import { ToastProvider } from "@/features/Toast/ToastProvider";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "@/features/Auth/AuthContext";
import AuthGuard from "@/features/Auth/AuthGuard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <ToastProvider>
            <AuthProvider>
              <AuthGuard>
                <div className="h-full flex flex-col">
                  <main className="flex-1">{children}</main>
                </div>
              </AuthGuard>
            </AuthProvider>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
