export const APP_CONSTANTS = {
  APP_NAME: 'Azure Dashboard',
  VERSION: '0.1.0',
  
  // Auth
  TOKEN_KEY: 'auth-token',
  TOKEN_EXPIRY_DAYS: 7,
  
  // API
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  
  // UI
  TOAST_DURATION: 5000,
  DEBOUNCE_DELAY: 300,
  
  // Validation
  MIN_PASSWORD_LENGTH: 8,
  MAX_NAME_LENGTH: 50,
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};
